admin.email.from.address=test@test.de
admin.email.from.name=Test Test
company.default.locale=en_US
company.default.time.zone=UTC
company.default.web.id=test.de
default.admin.email.address.prefix=test
jdbc.default.driverClassName=org.postgresql.Driver
jdbc.default.password=123
jdbc.default.url=jdbc:postgresql://localhost:5432/challenge_portal
jdbc.default.username=postgres
liferay.home=C:/Users/Oliver/eclipse-workspace/liferayworkspace-project/liferay-ce-portal-7.4.3.52-ga52
setup.wizard.add.sample.data=on
setup.wizard.enabled=false
